name: cradlers2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase and core features
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  js: ^0.7.2
  firebase_database: ^11.3.4

  # UI and utilities
  shared_preferences: ^2.2.2
  flutter_bloc: ^9.1.0
  shimmer: ^3.0.0
  camera: ^0.11.1
  device_info_plus: ^11.3.3
  package_info: ^2.0.2
  cupertino_icons: ^1.0.8
  flutter_mjpeg: ^2.0.1
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo-wo-bg.png
    - assets/cradle.png
    - assets/user_avatar.jpg
